### ISSUE TITLE
List view breaks when crops are on media type

### ISSUE THREAD

**Issue by amirkhan81** [garpunkal/punkThumbnailListView#1]
I get this error with a standard single media picker called "image" which has crops on it. The file name of the image actually renders in the correct field though. Any ideas?

`/umbraco/[%7B%22key%22:%223eaec576-f8a7-4665-b76c-d07571a27ac3%22,%22mediaKey%22:%227f44144e-3b02-4f35-ba76-dec2a5b5a9ce%22,%22crops%22:null,%22focalPoint%22:%7B%22left%22:0.5,%22top%22:0.5%7D%7D] 400 (Bad `

**Comment by garpunkal** [comment]
@amirkhan81 I will take a look a this, I don't tend to use crops on the actual image, just using the image cropper.

**Comment by garpunkal** [comment]
fixed in the new version
